= GNU Assembler(GAS)

== 命令选项

== 语法

=== 预处理

=== 空白符

=== 注释

=== 符号

符号由数字、英文字母（大小写敏感）、‘$’、‘.’、‘_’一个或多个字符组成。例如：

    abc:
        movb $0, %ax



大部分机器里都可以使用$符号，但也有例外：



数字不能作为首字符。符号名称没有长度限制：



支持多字符，但是--multibytes-handling选项可能会阻止使用：


符号名称可以放在双引号中，在这种情况下，除了NUL任何字符都是允许的：

    "0a":
        movb $0, %ax

双引号作为符号的一部时，需要加上前缀反斜杠“\”：

    "\"a":
        movb $0, %ax



=== 语句

一条语句应当以换行符（\n）或行分割符结尾。

行分割符是特定于机器的，不是所有机器都支持。

换行符和行分割符被视为前面语句的一部分。

任何源文件都必须以换行符结束，否则是错的。

如果点（.）作为符号的首字符，那么这个语句就是一个汇编器指示（伪指令）。

如果文字作为符号的首字符，那么这个语句就是一个汇编语言指令，最终会汇编为机器语言指令。不同版本的汇编器（as）识别不同的指令。事实上，相同符号可能表示不同计算机的不同指令。

====  标签

标签是一个符号后紧随冒号“:”。标签前后可以有任意多个空白符，但是它的符号和冒号中间不能有空白符（HPPA的冒号可以不跟着符号，但是符号必须是行首第一个字符）。


=== 常量

常量可以是数、字符串：

    .byte 74,0112, 'a' #字符
    .ascii "Hello World" #字符串
    .octa 0x1234567899043434343787438738473 # 大数
    .float 0f-31415926535897932384626433832795028841971.693993751E-40 # 圆周率

==== 字符常量

有两种类型的字符常量：

- 字符常量：字符常量是一个字节表示的字符，它的值可以用于数量表达式
- 串常量：又叫串字面量， 由多个字符组成，不能用于算术表达式

===== 串

字符串写在两个双引号间，可以包含双引号和空字符。用转义（在字符前加入反斜杠‘\’）包含特殊字符

====== 字符

字符用单引号括起来。对于特殊字符必须转义（在字符前加反斜杠‘\’）。字符常量的值在数字表达式中表示为对应ASCII字符的机器字节码。

====== 数字

====== 整数

====== 大数

====== 浮点数



== 节与重定位

== 符号



== 表达式

== 汇编指令

== 机器依赖的特性

